version: "3.8"
services:
  backend:
    image: yz743/easycrm:backend-v1.0.3
    container_name: backend
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
      - PORT=8888
      - JWT_SECRET=secret_key_1234
      - PUBLIC_SERVER_FILE=http://localhost:8888/
      - BYPASS_AUTH=true
    networks:
      - app-network

  frontend:
    image: yz743/easycrm:frontend-v1.0.3
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_APP_API_URL=http://localhost:8888/api
      - VITE_BACKEND_SERVER=http://localhost:8888/
      - VITE_FILE_BASE_URL=http://localhost:8888/
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 