// file.* MCP tools (#249 Plan B v3 phase B)
//
// Exposes the audio-file / transcript surface to the agent. All tools are
// per-user-scoped via the same controllerAdapter chain customer.* and quote.*
// use (AsyncLocalStorage acting-as admin → req.admin._id → controller filter
// by createdBy). Cross-admin reads are not possible by construction.
//
// Surface:
//   file.search                 List user's uploaded files with optional name / status filter
//   file.get_transcript         Read full transcript text for one File (must be done)
//   file.transcription_status   Lightweight status probe (no sidecar read)
//
// Status vocabulary is the COLLAPSED set {ready, processing, done, failed}.
// chat.js uses the same set in its hint, so the agent sees one vocabulary.
// `ready` = no transcription Job exists (e.g. non-audio file).
// `processing` = pending or running (transitional — distinction is not
// useful for the agent and only invites premature polling).

const mongoose = require('mongoose');
const { z } = require('zod');
const fileController = require('@/controllers/appControllers/fileController');
const jobController = require('@/controllers/appControllers/jobController');
const { runController } = require('../../adapters/controllerAdapter');
const { collapseJobStatus } = require('@/utils/collapseJobStatus');
const { COLLAPSED_JOB_STATUS_VALUES } = require('@/constants/jobStatus');

const search = {
  name: 'file.search',
  description:
    'Search the user\'s uploaded audio files. Returns a concise list with transcription status, ' +
    'so the agent can decide which file to read next. Use this to discover files when the user ' +
    'refers to a recording by name or context ("我之前那段录音").',
  inputSchema: {
    query: z
      .string()
      .optional()
      .describe('Partial match on originalName (case-insensitive). Omit to list all.'),
    status: z
      .enum(COLLAPSED_JOB_STATUS_VALUES)
      .optional()
      .describe(
        'Filter by collapsed transcription status. ready=no job, processing=pending|running, done, failed.'
      ),
  },
  handler: async ({ query, status }) => {
    const listRes = await runController(fileController.list, {
      query: { items: 100, page: 1 },
    });
    if (!listRes.ok) return listRes;

    const files = Array.isArray(listRes.data) ? listRes.data : [];

    const candidates = query
      ? files.filter((f) =>
          (f.originalName || '').toLowerCase().includes(query.toLowerCase())
        )
      : files;

    const jobIds = candidates
      .map((f) => f.transcriptionJobId)
      .filter(Boolean)
      .map((id) => String(id));
    const jobById = new Map();
    if (jobIds.length) {
      const JobModel = mongoose.model('Job');
      const jobs = await JobModel.find({ _id: { $in: jobIds } })
        .select('status result error')
        .lean();
      for (const j of jobs) jobById.set(String(j._id), j);
    }

    const enriched = [];
    for (const f of candidates) {
      const job = f.transcriptionJobId
        ? jobById.get(String(f.transcriptionJobId)) || null
        : null;
      const collapsed = collapseJobStatus(job);
      if (status && collapsed !== status) continue;
      enriched.push({
        fileId: f._id,
        originalName: f.originalName,
        mimeType: f.mimeType,
        sizeBytes: f.sizeBytes,
        created: f.created,
        transcription: job
          ? {
              status: collapsed,
              durationMs: job.result?.durationMs ?? null,
              error: job.error || '',
            }
          : null,
      });
    }

    return {
      ok: true,
      data: {
        found: enriched.length > 0,
        count: enriched.length,
        files: enriched,
      },
    };
  },
};

const get_transcript = {
  name: 'file.get_transcript',
  description:
    'Get the full transcript text of a transcribed audio file. The transcript is authoritative ' +
    '(generated by the backend transcription microservice using OpenAI gpt-4o-transcribe-diarize). ' +
    'Returns 404 if file not found / not owned by user, 409 if still transcribing (status=processing), ' +
    '422 if transcription failed. Format: "<speaker> mm:ss  <text>" lines.',
  inputSchema: {
    fileId: z.string().min(1).describe('File._id'),
  },
  handler: async ({ fileId }) =>
    runController(fileController.getTranscript, {
      params: { id: fileId },
    }),
};

const transcription_status = {
  name: 'file.transcription_status',
  description:
    'Cheap status probe for a file\'s transcription Job. Use before file.get_transcript to ' +
    'avoid 409 when status=processing. Returns {status, durationMs?, error?}.',
  inputSchema: {
    fileId: z.string().min(1).describe('File._id'),
  },
  handler: async ({ fileId }) => {
    const fileRes = await runController(fileController.read, {
      params: { id: fileId },
    });
    if (!fileRes.ok) return fileRes;
    const fileDoc = fileRes.data;
    if (!fileDoc.transcriptionJobId) {
      return { ok: true, data: { status: collapseJobStatus(null) } };
    }
    const jobRes = await runController(jobController.read, {
      params: { id: String(fileDoc.transcriptionJobId) },
    });
    if (!jobRes.ok) return jobRes;
    const job = jobRes.data;
    return {
      ok: true,
      data: {
        status: collapseJobStatus(job),
        durationMs: job.result?.durationMs ?? null,
        error: job.error || '',
      },
    };
  },
};

module.exports = [search, get_transcript, transcription_status];
