apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: easycrm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ydz0616/crm.git'  # 保持原始URL不变
    targetRevision: HEAD
    path: kubernetes
    directory:
      recurse: true
      exclude: 'secrets*.yaml'  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crm-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: crm-secrets
      namespace: crm-system
    - group: ""
      kind: ConfigMap
      name: crm-config
      namespace: crm-system 