apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ydz0616/crm.git'  # 替换为你的 Git 仓库地址
    targetRevision: HEAD
    path: kubernetes
    directory:
      recurse: true
      exclude: 'secrets*.yaml'  # 排除所有 secrets 相关文件
  destination:
    server: https://kubernetes.default.svc
    namespace: crm-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: crm-secrets
      namespace: crm-system 