apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-backend
  labels:
    app: crm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-backend
  template:
    metadata:
      labels:
        app: crm-backend
    spec:
      containers:
      - name: crm-backend
        image: yz743/easycrm:backend-v1.0.4
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: crm-secrets
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: crm-secrets
              key: jwt-secret
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: OPENSSL_CONF
          value: "/dev/null"
        - name: PUBLIC_SERVER_FILE
          value: "http://129.226.142.103:30888/"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: crm-backend
spec:
  selector:
    app: crm-backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30888
  type: NodePort 