apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: crm-system
  annotations:
    argocd.argoproj.io/hook: Skip
    argocd.argoproj.io/sync: "false"
  labels:
    app.kubernetes.io/instance: easycrm
    app.kubernetes.io/managed-by: init-job
data:
  # 基本配置
  API_TIMEOUT: "30000"
  LOG_LEVEL: "info"
  MAX_UPLOAD_SIZE: "10485760"  # 10MB in bytes
  
  # 这些URL值仅作示例，将由config-update-job动态替换
  api-base-url: "http://PLACEHOLDER:30888/api/"
  backend-url: "http://PLACEHOLDER:30888/"
  file-base-url: "http://PLACEHOLDER:30888/"
  allowed-origins: "http://localhost:3000,http://frontend:3000,http://PLACEHOLDER:30080,http://PLACEHOLDER" 