apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: crm-frontend
    app.kubernetes.io/instance: easycrm
    app.kubernetes.io/part-of: crm
    app.kubernetes.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crm-frontend
        app.kubernetes.io/instance: easycrm
        app.kubernetes.io/part-of: crm
        app.kubernetes.io/component: frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - crm-frontend
              topologyKey: kubernetes.io/hostname
      containers:
      - name: crm-frontend
        image: yz743/easycrm:frontend-v1.0.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: frontend-config
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/instance: easycrm
    app.kubernetes.io/part-of: crm
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: crm-frontend
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app.kubernetes.io/instance: easycrm
    app.kubernetes.io/part-of: crm
    app.kubernetes.io/component: frontend
data:
  NODE_ENV: "production"
  VITE_APP_API_URL: "http://8.210.8.147:30888/api/"
  VITE_BACKEND_SERVER: "http://8.210.8.147:30888/"
  VITE_FILE_BASE_URL: "http://8.210.8.147:30888/"
  VITE_WEBSITE_URL: "http://8.210.8.147:30080/" 