apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-frontend
  labels:
    app: crm-frontend
    app.kubernetes.io/instance: easycrm
    app.kubernetes.io/part-of: crm
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-frontend
  template:
    metadata:
      labels:
        app: crm-frontend
        app.kubernetes.io/instance: easycrm
        app.kubernetes.io/part-of: crm
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: crm-frontend
        image: yz743/easycrm:frontend-v1.0.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: crm-config
              key: api-base-url
        - name: VITE_BACKEND_SERVER
          valueFrom:
            configMapKeyRef:
              name: crm-config
              key: backend-url
        - name: VITE_FILE_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: crm-config
              key: file-base-url
        - name: VITE_WEBSITE_URL
          valueFrom:
            configMapKeyRef:
              name: crm-config
              key: website-url
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: crm-frontend
  labels:
    app.kubernetes.io/instance: easycrm
    app.kubernetes.io/part-of: crm
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: crm-frontend
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30080
  type: NodePort 