apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-frontend
  labels:
    app: crm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-frontend
  template:
    metadata:
      labels:
        app: crm-frontend
    spec:
      containers:
      - name: crm-frontend
        image: yz743/easycrm:frontend-v1.0.4
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_APP_API_URL
          value: "http://129.226.142.103:30888/api"
        - name: VITE_BACKEND_SERVER
          value: "http://129.226.142.103:30888/"
        - name: VITE_FILE_BASE_URL
          value: "http://129.226.142.103:30888/"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: crm-frontend
spec:
  selector:
    app: crm-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
  type: NodePort 