apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: crm-frontend
    app.kubernetes.io/instance: easycrm
    app.kubernetes.io/part-of: crm
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-frontend
  template:
    metadata:
      labels:
        app: crm-frontend
        app.kubernetes.io/instance:
           easycrm
        app.kubernetes.io/part-of: crm
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: crm-frontend
        image: yz743/easycrm:frontend-v1.1.0
        imagePullPolicy: IfNotPresent
        command: ["npm"]
        args: ["run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: frontend-config
        env:
        - name: PORT
          value: "3000"
        - name: NODE_OPTIONS
          value: "--max-old-space-size=384"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/instance: easycrm
    app.kubernetes.io/part-of: crm
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: crm-frontend
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app.kubernetes.io/instance: easycrm
    app.kubernetes.io/part-of: crm
    app.kubernetes.io/component: frontend
data:
  NODE_ENV: "production"
  VITE_APP_API_URL: "http://47.76.240.140:30888/api/"
  VITE_BACKEND_SERVER: "http://47.76.240.140:30888/"
  VITE_FILE_BASE_URL: "http://47.76.240.140:30888/"
  VITE_WEBSITE_URL: "http://47.76.240.140:30080/" 