apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crm-system
namePrefix: crm-

resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: crm-application

patchesStrategicMerge: [] 